name: Assortment of tools

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - uses: ./
    - name: 'Local lint'
      uses: actions/lint/
