name: Assortment of tools

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: PHP Syntax Checker (Lint)
      uses: StephaneBour/actions-php-lint@7.3
      with:
        # Folder to check syntax
        dir: src
